<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB; // Import the DB facade
use Illuminate\Support\Str;

class RecipesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        // Insert the recipe and get the recipe ID
        $slug1 = Str::slug('Plant-Based Sweet & Sour Stir-fry chicken/tofu');
        $recipeId1 = DB::table('recipes')->insertGetId([
            'title' => 'Plant-Based Sweet & Sour Stir-fry chicken/tofu',
            'slug' => $slug1,
            'description' => 'This sweet and sour chicken stir-fry recipe is a version of the Asian-style favorite that includes carrots, bell pepper, garlic, and pineapple. The requisite soy sauce and vinegar add the sour to the sweet!',
            'created_by' => 1,
            'image' => 'img/Plant-Based Sweet & Sour Stir-fry chicken-tofu.jpg',
            'ingredients' => json_encode(['Vegetable oil', 'Chicken', 'Sugar', 'Soy Sauce']),
            'steps' => json_encode([
                "Instructions",
                "Start by preparing the sauce:",
                'Set aside ½ cup of pineapple juice from your can of pineapple, and reserve ⅔ cup of the pineapple chunks (if using). Set aside.',
                'Combine the hot water, salt, sugar, and ketchup. Stir until the salt and sugar are dissolved, and then add the vinegar and pineapple juice (if using). If not using pineapple juice, replace with ½ cup water or chicken stock. Set aside.',
                "Marinate the chicken:",
                'Cut your chicken into uniform 1 inch chunks (for even cooking) and place into a bowl. Add the garlic and onion powders, sesame oil, white pepper, and salt. Mix until all pieces are uniformly coated, and let it sit for 5 minutes. Any excess water should be fully absorbed by the chicken. If not, mix the chicken again and let it sit for another 5 minutes.',
                "Make the batter:",
                'Mix together the all-purpose flour, cornstarch, baking powder, and baking soda in a bowl, and add 2/3 cup of ice water. Use a fork to mix until a batter is formed, and stir in 1 tablespoon of oil. Set aside.',
                "Fry the chicken:",
                'The amount of oil you need depends on the size of the pot you will use. Using a larger pot uses more oil, but allows you to cook the chicken in fewer batches. Using a smaller pot uses less oil, but you’ll have to fry more batches of chicken. We usually go for a smaller pot, so we have less leftover oil. Heat the oil in a small pot until it reaches 335°F/170°C.',
                'Place 5 to 6 pieces of marinated chicken into the batter. Use a chopstick, fork, or your fingers to coat the chicken in the batter and place each piece slowly into the oil.',
                'Use a slotted spoon to carefully turn the chicken so all sides are uniformly fried. Fry for about 2 minutes, or until the batter is a light golden brown and crispy. Remove with a slotted spoon and let any excess oil drain off before placing onto a rack or paper towel-lined plate.',
                "Assemble in the Wok:",
                'Heat 1 tablespoon canola oil in a wok over medium-high heat, and add the red onion and peppers. Stir-fry for 30 seconds.',
                'Next, add the sweet and sour sauce you prepared earlier and bring to a boil. Reduce the heat so the sauce is simmering.',
                'Combine the cornstarch and water to make a uniform slurry. While stirring the sweet and sour sauce, drizzle the slurry in gradually until the sauce is thick enough to coat a spoon (you may not need all of the slurry). Turn down the heat and give the sauce a quick taste––now is the time to add more salt, vinegar, or sugar if desired.',
                'Add the pineapple chunks (if using) and stir until warmed through. Now is the time to refry the chicken to make them nice and crispy. Heat the oil up to 335°F/170°C and fry the chicken in two batches for about 45 seconds each time. Then add the chicken pieces to your sauce, and gently toss with your wok spatula until the chicken is coated. Serve immediately!'
            ]),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    
        // Insert substitutions for the recipe
        DB::table('substitutions')->insert([
            [
                'recipe_id' => $recipeId1,
                'primary_ingredient' => 'Soy sauce',
                'substitute' => 'Tamari',
                'compatibility' => 2,
                'criteria' => 'Flavor profile (rich, thick texture and nuanced salinity)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId1,
                'primary_ingredient' => 'Soy sauce',
                'substitute' => 'Coconut Aminos',
                'compatibility' => 3,
                'criteria' => 'Healthier option (low in sodium), Dietary restriction (soy-free, gluten-free)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId1,
                'primary_ingredient' => 'Vegetable oil',
                'substitute' => 'Sesame oil',
                'compatibility' => 2,
                'criteria' => 'Flavor profile (rich)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId1,
                'primary_ingredient' => 'Chicken',
                'substitute' => 'Seitan',
                'compatibility' => 3,
                'criteria' => 'Different texture, Healthier option (richest in protein), Dietary restriction (vegan)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId1,
                'primary_ingredient' => 'Chicken',
                'substitute' => 'Tofu',
                'compatibility' => 2,
                'criteria' => 'Dietary restriction (vegan)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId1,
                'primary_ingredient' => 'Sugar',
                'substitute' => 'Honey',
                'compatibility' => 2,
                'criteria' => 'Flavor profile (natural sweetener)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId1,
                'primary_ingredient' => 'Sugar',
                'substitute' => 'Maple syrup',
                'compatibility' => 2,
                'criteria' => 'Flavor profile (natural sweetener)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId1,
                'primary_ingredient' => 'Sugar',
                'substitute' => 'Stevia',
                'compatibility' => 3,
                'criteria' => 'Dietary restriction (sugar-free)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Recipe 2: Three Cup Chicken
        $slug2 = Str::slug('Three Cup Chicken');
        $recipeId2 = DB::table('recipes')->insertGetId([
            'title' => 'Three Cup Chicken',
            'slug' => $slug2,
            'description' => 'This three cup tofu recipe is a plant-based version of the famous dish, Three Cup Chicken. Whether you’re vegetarian or not, it’s just plain delicious.',
            'created_by' => 1,
            'image' => 'img/three-cup-chicken.jpg',
            'ingredients' => json_encode(['Chicken', 'Sesame oil', 'Soy sauce', 'Thai basil', 'Rice wine', 'Sugar', 'Chilli pepper']),
            'steps' => json_encode([
                'Slice the block of chicken in half lengthwise, then slice into 1/2 inch thick rectangles.',
                'Heat a large non-stick pan over medium-high heat, and add the oil.' ,
                'Add the cornstarch to a shallow dish. Once the pan is heated, quickly coat the chicken slices with cornstarch, shaking off any excess.' ,
                'Carefully place into the oiled pan, and repeat with the remaining chicken and cornstarch.',
                'Pan-fry the chicken pieces in oil until crisp and golden on both sides, about 4-5 minutes per side.',
                'Once the chicken is done pan-frying, remove them immediately from the pan onto a plate (otherwise they will absorb the remaining oil in the pan off the heat). Set aside.',
                'To a wok over medium heat, add the oil leftover from pan-frying the chicken (scrape it out with a spatula), along with the sesame oil, ginger, garlic, and dried chili.',
                'TIP: If you dont have a wok, you can simply cook the dish in the same non-stick skillet you pan-fried the chicken in.',
                'Let the aromatics infuse the oil for 1 minute. Then add the Shaoxing wine, water, light soy sauce, dark soy sauce, sugar, and white pepper. Bring the liquid to a simmer.',
                'Increase the heat to medium-high, and stir in the chicken. Toss the chicken with the sauce for 1-2 minutes, until the sauce reduces and thickens to coat the chicken.',

            ]),
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        // Substitutions for Recipe 2
        DB::table('substitutions')->insert([
            [
                'recipe_id' => $recipeId2,
                'primary_ingredient' => 'Sesame oil',
                'substitute' => 'Olive oil',
                'compatibility' => 2,
                'criteria' => 'Healthier option, different flavor profile',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId2,
                'primary_ingredient' => 'Thai basil',
                'substitute' => 'Regular basil',
                'compatibility' => 2,
                'criteria' => 'Similar flavor, but not as spicy or pungent',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId2,
                'primary_ingredient' => 'Thai basil',
                'substitute' => 'Cilantro',
                'compatibility' => 1,
                'criteria' => 'Different flavor profile, provides freshness',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId2,
                'primary_ingredient' => 'Chicken',
                'substitute' => 'Tofu',
                'compatibility' => 3,
                'criteria' => 'Vegan option, different texture, but can absorb similar flavors',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId2,
                'primary_ingredient' => 'Rice wine',
                'substitute' => 'Apple cider vinegar',
                'compatibility' => 2,
                'criteria' => 'Similar acidity, different flavor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId2,
                'primary_ingredient' => 'Sugar',
                'substitute' => 'Honey',
                'compatibility' => 2,
                'criteria' => 'Natural sweetener, similar sweetness',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId2,
                'primary_ingredient' => 'Sugar',
                'substitute' => 'Maple syrup',
                'compatibility' => 2,
                'criteria' => 'Natural sweetener, slightly different flavor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId2,
                'primary_ingredient' => 'Chili peppers',
                'substitute' => 'Red pepper flakes',
                'compatibility' => 2,
                'criteria' => 'Similar spiciness, easier to use',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId2,
                'primary_ingredient' => 'Soy sauce',
                'substitute' => 'Tamari',
                'compatibility' => 2,
                'criteria' => 'Gluten-free, similar flavor profile',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId2,
                'primary_ingredient' => 'Soy sauce',
                'substitute' => 'Coconut Aminos',
                'compatibility' => 3,
                'criteria' => 'Healthier, lower sodium, soy-free',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        // Recipe 3: Cantonese Shrimp and Eggs
        $slug3 = Str::slug('Cantonese Shrimp and Eggs');
        $recipeId3 = DB::table('recipes')->insertGetId([
            'title' => 'Cantonese Shrimp and Eggs',
            'slug' => $slug3,
            'description' => 'Cantonese Shrimp and Eggs is a classic dish that transforms scrambled eggs into an epic dinnertime experience. The trick is the simple addition of a cornstarch slurry, which makes the eggs extra tender and silky! When you make this dish at home, you’ll truly feel like you’re a master of your wok and kitchen! ',
            'created_by' => 1,
            'image' => 'img/Cantonese-Shrimp-and-Eggs.jpg',
            'ingredients' => json_encode(['Shrimp', 'Eggs', 'Soy sauce', 'Sesame oil', 'Scallions', 'Cornstarch']),
            'steps' => json_encode([
                'Add the peeled, deveined shrimp to a medium bowl, along with the oil, sugar, salt, white pepper, and cornstarch. Mix until well combined.',
                'Crack the eggs into a large bowl, and add the white pepper, sesame oil, and salt. Prepare the cornstarch slurry. You’ll add it right before you’re ready to cook the eggs. Beat the eggs until large bubbles form—about 30 seconds, maybe a little longer if you’re not so confident beating eggs.' ,
                'Preheat your wok over medium heat until its just starting to smoke. Add 1 tablespoon of oil around the perimeter. Spread the shrimp in one layer, and cook until they’ve juuust turned orange. They should still look a bit raw in the center. Transfer back to the marinating bowl. They will finish cooking later.' ,
                'Stir up your cornstarch slurry to make sure the cornstarch is dispersed in the water, and add it to the eggs. Beat a few times to make sure the cornstarch is incorporated and the eggs are aerated. Increase the heat to high.',
                'When the wok begins to smoke again, add the remaining 3 tablespoons of oil, followed by the eggs. They will immediately puff up and cook. Quickly use your wok spatula to gently push the eggs across the wok. Do this a few times.',
                'When the eggs are beginning to set but still mostly runny, add the shrimp. As you push the eggs around, layers of egg will cook and pile on top of each other, creating a fluffy effect, and the shrimp will get distributed throughout the eggs. As the egg cooks, you can fold it on top of itself.',
                'When the eggs are still a bit wobbly looking, but mostly cooked, sprinkle the scallions over the top. Give one or two final stirs to combine, then transfer to a serving plate. The dish will continue to cook in the minutes before you eat!',
            ]),
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        // Substitutions for Recipe 3
        DB::table('substitutions')->insert([
            [
                'recipe_id' => $recipeId3,
                'primary_ingredient' => 'Sesame oil',
                'substitute' => 'Olive oil',
                'compatibility' => 2,
                'criteria' => 'Healthier option, different flavor profile',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId3,
                'primary_ingredient' => 'Sesame oil',
                'substitute' => 'Perilla oil',
                'compatibility' => 3,
                'criteria' => 'Nutty flavor, similar in aroma',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId3,
                'primary_ingredient' => 'Shrimp',
                'substitute' => 'Tofu',
                'compatibility' => 3,
                'criteria' => 'Vegan option, different texture but absorbs flavors well',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId3,
                'primary_ingredient' => 'Shrimp',
                'substitute' => 'Seitan',
                'compatibility' => 2,
                'criteria' => 'Similar protein source, but different texture',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId3,
                'primary_ingredient' => 'Eggs',
                'substitute' => 'Silken',
                'compatibility' => 3,
                'criteria' => 'Vegan option, similar creamy texture in scrambled form',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId3,
                'primary_ingredient' => 'Soy sauce',
                'substitute' => 'Tamari',
                'compatibility' => 2,
                'criteria' => 'Gluten-free, similar flavor profile',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId3,
                'primary_ingredient' => 'Soy sauce',
                'substitute' => 'Coconut Aminos',
                'compatibility' => 3,
                'criteria' => 'Healthier, lower sodium, soy-free',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId3,
                'primary_ingredient' => 'Scallions',
                'substitute' => 'Chives',
                'compatibility' => 2,
                'criteria' => 'Milder flavor but similar freshness',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId3,
                'primary_ingredient' => 'Cornstarch',
                'substitute' => 'Potato starch',
                'compatibility' => 3,
                'criteria' => 'Similar thickening agent, works in the same way',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId3,
                'primary_ingredient' => 'Cornstarch',
                'substitute' => 'Arrowroot powder',
                'compatibility' => 3,
                'criteria' => 'Gluten-free, healthier alternative for thickening',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        // Recipe 4: Stuffed Bitter Melon
        $slug4 = Str::slug('Stuffed Bitter Melon');
        $recipeId4 = DB::table('recipes')->insertGetId([
            'title' => 'Stuffed Bitter Melon',
            'slug' => $slug4,
            'description' => 'This stuffed bitter melon recipe in black bean sauce is a classic Cantonese dish that highlights a produce item in abundance right now in Chinese groceries and backyard gardens: bitter melon!',
            'created_by' => 1,
            'image' => 'img/Stuffed-Bitter-Melon.jpg',
            'ingredients' => json_encode(['Chinese bitter melon', 'Ground pork', 'Dark soy sauce','Light Soy sauce', 'Sesame oil', 'Shaoxing wine', 'Oil','Salt', 'Garlic','Ginger','Sugar','Chicken stock']),
            'steps' => json_encode([
                'If soaking shiitake mushrooms overnight, you can start in cold water. Place a small bowl or plate on top of the mushrooms to keep them submerged. To soak them faster, start with hot water, and soak for 2 hours until reconstituted. Squeeze any excess moisture off the of the mushrooms, trim away the stems if they’re touch, and finely chop them. You should have about 1/3 cup.',
                'Add the mushrooms and ground pork to the bowl of a stand mixer fitted with a paddle attachment or a mixing bowl. Add the cornstarch, oyster sauce, Shaoxing wine, sugar, sesame oil, salt, and white pepper. Turn the mixer on low speed for 3 minutes, or mix with a pair of chopsticks vigorously for 5 minutes, until the mixture starts to have a paste-like consistency.' ,
                'Bring 8 cups of water to a boil with 1 tablespoon baking soda. Slice the bitter melon into rings about 3/4 inch thick. Scoop out the centers of the bitter melon with a small spoon or paring knife. I like to cut the middle out with the paring knife and then scrape the remaining pith with a spoon. Blanch the bitter melon rings in the water for 1 minute, and then transfer to an ice bath.' ,
                'Add 1 1/2 tablespoons cornstarch to a shallow dish. Sprinkle a little cornstarch on the inside of each bitter melon ring, which will help the filling stick to the inside. Use a butter knife to fill the bitter melon rings with the filling, flattening the filling so it’s flush with the melon slice and the meat overlaps slightly with the outer ring of the bitter melon (this will keep the filling from falling out).',
                'Heat a wok or or cast iron pan over medium-high heat until lightly smoking (or heat a non-stick pan over medium-high heat). Add 2 tablespoons of neutral oil. Add the bitter melon pieces, and fry until golden on each side, about 2-3 minutes per side. Remove from the pan and set aside.',
                'To the oil left in the wok, add the ginger, garlic, and fermented black beans. Cook for 30 seconds, and then add the Shaoxing wine. Cook for another 30 seconds, and then add the stock, oyster sauce, sugar, light soy sauce, and dark soy sauce. Bring to a simmer. Once simmering, add the bitter melon pieces back to the wok, cover, and simmer for 4-5 minutes to cook the meat through (cook for 5 minutes if you like your bitter melon more tender). Mix the remaining 1 tablespoon cornstarch into a slurry with 1 tablespoon water, and add to the simmering sauce to thicken. Simmer until the sauce is glossy and coats the bitter melon pieces.',
                'Plate the bitter melon and pour the sauce over the top. Serve!',
            ]),
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        // Substitutions for Recipe 4
        DB::table('substitutions')->insert([
            [
                'recipe_id' => $recipeId4,
                'primary_ingredient' => 'Sesame oil',
                'substitute' => 'Olive oil',
                'compatibility' => 2,
                'criteria' => 'Healthier option, different flavor profile',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId4,
                'primary_ingredient' => 'Sesame oil',
                'substitute' => 'Perilla oil',
                'compatibility' => 3,
                'criteria' => 'Nutty flavor, similar in aroma',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId4,
                'primary_ingredient' => 'Chinese bitter melon',
                'substitute' => 'Zucchini',
                'compatibility' => 2,
                'criteria' => 'Milder flavor, similar texture, different bitterness',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId4,
                'primary_ingredient' => 'Chinese bitter melon',
                'substitute' => 'Bell peppers (hollowed out)',
                'compatibility' => 2,
                'criteria' => 'Different flavor, but can be stuffed similarly',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId4,
                'primary_ingredient' => 'Ground pork',
                'substitute' => 'Ground chicken',
                'compatibility' => 3,
                'criteria' => 'Leaner, lighter flavor, works well as a substitute',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId4,
                'primary_ingredient' => 'Ground pork',
                'substitute' => 'Ground turkey',
                'compatibility' => 2,
                'criteria' => 'Similar texture, leaner meat, slightly different flavor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId4,
                'primary_ingredient' => 'Ground pork',
                'substitute' => 'Tofu (crumbled)',
                'compatibility' => 3,
                'criteria' => 'Vegan option, absorbs flavors well',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId4,
                'primary_ingredient' => 'Dark soy sauce',
                'substitute' => 'Mushroom soy sauce',
                'compatibility' => 2,
                'criteria' => 'Adds depth with an umami flavor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId4,
                'primary_ingredient' => 'Dark soy sauce',
                'substitute' => 'Double black soy sauce',
                'compatibility' => 3,
                'criteria' => 'Richer, thicker, adds deep color and flavor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId4,
                'primary_ingredient' => 'Light Soy sauce',
                'substitute' => 'Tamari',
                'compatibility' => 2,
                'criteria' => 'Gluten-free, similar flavor profile',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId4,
                'primary_ingredient' => 'Light Soy sauce',
                'substitute' => 'Coconut Aminos',
                'compatibility' => 3,
                'criteria' => 'Healthier, lower sodium, soy-free',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId4,
                'primary_ingredient' => 'Shaoxing wine',
                'substitute' => 'Mirin',
                'compatibility' => 2,
                'criteria' => 'Sweeter, less alcoholic but can work as a cooking wine substitute',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId4,
                'primary_ingredient' => 'Oil',
                'substitute' => 'Olive oil',
                'compatibility' => 2,
                'criteria' => 'Healthier option, but different flavor profile',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId4,
                'primary_ingredient' => 'Oil',
                'substitute' => 'Avocado oil',
                'compatibility' => 3,
                'criteria' => 'Healthier option, neutral taste and high heat tolerance',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId4,
                'primary_ingredient' => 'Salt',
                'substitute' => 'Himalayan Salt',
                'compatibility' => 2,
                'criteria' => 'Low in sodium, similar salty profile',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId4,
                'primary_ingredient' => 'Garlic',
                'substitute' => 'Shallots',
                'compatibility' => 2,
                'criteria' => 'Milder, but similar aromatic quality',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId4,
                'primary_ingredient' => 'Ginger',
                'substitute' => 'Galangal',
                'compatibility' => 2,
                'criteria' => 'Slightly different flavor profile, but still pungent and spicy',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId4,
                'primary_ingredient' => 'Chicken stock',
                'substitute' => 'Vegetable stock',
                'compatibility' => 3,
                'criteria' => 'Vegan substitute, similar flavor base',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId4,
                'primary_ingredient' => 'Chicken stock',
                'substitute' => 'Mushroom broth        ',
                'compatibility' => 3,
                'criteria' => 'Vegan substitute with umami flavor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        // Recipe 5: Kung-Pao-Shrimp
        $slug5 = Str::slug('Kung Pao Shrimp');
        $recipeId5 = DB::table('recipes')->insertGetId([
            'title' => 'Kung Pao Shrimp',
            'slug' => $slug5,
            'description' => 'This Kung Pao Shrimp is a symphony of flavors, accentuated by the crunch of peanuts and the spice of Sichuan peppercorns and dried red chilies. It’s delicious with rice, and disappeared fast when we cooked and photographed it! A telltale sign of a winning recipe.',
            'created_by' => 1,
            'image' => 'img/Kung-Pao-Shrimp.jpg',
            'ingredients' => json_encode(['Shrimp', 'Shaoxing wine', 'Dark soy sauce','Light Soy sauce', 'Oil', 'Garlic','Ginger','Rice wine vinegar','Dried red chilies','Cornstarch']),
            'steps' => json_encode([
                'Prepare the shrimp:',
                'Butterfly each shrimp, making a small cut along its back without cutting it all the way through. Add the shrimp to a bowl, along with the oil, Shaoxing wine, salt, and white pepper powder. Set aside for 15 minutes.' ,
                'Mix in the cornstarch right before cooking.' ,
                'Prepare the sauce:',
                'In a medium bowl, make the sauce by combining the water, rice wine vinegar, light soy sauce, sugar, cornstarch, Sichuan peppercorn powder, and dark soy sauce.',
                'Assemble the dish:',
                'Heat the wok over high heat, until it just starts to smoke. Add 2 tablespoons of oil, followed by the shrimp (be sure to stir the ½ teaspoon cornstarch into the shrimp before searing). Quickly sear the shrimp on both sides, and transfer to a bowl once they turn light pink. Set aside.',
                'Reduce the heat to low. Add the remaining tablespoon of oil, garlic, ginger, chilies, and scallions. Cook for 1-2 minutes, until fragrant, maintaining low heat.',
                'Increase the heat to high, and add the shrimp back to the wok. Stir-fry for 30 seconds. Stir up your prepared sauce (the cornstarch settles to the bottom and should be re-stirred). Add the sauce to the wok, and stir-fry for another minute. The sauce should thicken very quickly. Add the peanuts, and turn off the heat. Mix everything well, and serve!',
            ]),
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        // Substitutions for Recipe 5
        DB::table('substitutions')->insert([
            [
                'recipe_id' => $recipeId5,
                'primary_ingredient' => 'Shrimp',
                'substitute' => 'Tofu',
                'compatibility' => 3,
                'criteria' => 'Vegan option, different texture but absorbs flavors well',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId5,
                'primary_ingredient' => 'Shrimp',
                'substitute' => 'Seitan',
                'compatibility' => 2,
                'criteria' => 'Similar protein source, but different texture',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId5,
                'primary_ingredient' => 'Rice wine vinegar',
                'substitute' => 'Apple cider vinegar',
                'compatibility' => 3,
                'criteria' => 'Similar acidity, slightly sweeter flavor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId5,
                'primary_ingredient' => 'Rice wine vinegar',
                'substitute' => 'White vinegar',
                'compatibility' => 2,
                'criteria' => 'More acidic, but works as a substitute',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId5,
                'primary_ingredient' => 'Dried red chilies',
                'substitute' => 'Fresh red chilies (dried or sliced)',
                'compatibility' => 2,
                'criteria' => 'Fresher, slightly less spicy, but can work in stir-fries',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId5,
                'primary_ingredient' => 'Dried red chilies',
                'substitute' => 'Chili flakes (crushed red pepper)',
                'compatibility' => 3,
                'criteria' => 'Easier to find, provides a similar level of heat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId5,
                'primary_ingredient' => 'Dark soy sauce',
                'substitute' => 'Mushroom soy sauce',
                'compatibility' => 2,
                'criteria' => 'Adds depth with an umami flavor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId5,
                'primary_ingredient' => 'Dark soy sauce',
                'substitute' => 'Double black soy sauce',
                'compatibility' => 3,
                'criteria' => 'Richer, thicker, adds deep color and flavor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId5,
                'primary_ingredient' => 'Light Soy sauce',
                'substitute' => 'Tamari',
                'compatibility' => 2,
                'criteria' => 'Gluten-free, similar flavor profile',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId5,
                'primary_ingredient' => 'Light Soy sauce',
                'substitute' => 'Coconut Aminos',
                'compatibility' => 3,
                'criteria' => 'Healthier, lower sodium, soy-free',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId5,
                'primary_ingredient' => 'Shaoxing wine',
                'substitute' => 'Mirin',
                'compatibility' => 2,
                'criteria' => 'Sweeter, less alcoholic but can work as a cooking wine substitute',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId5,
                'primary_ingredient' => 'Oil',
                'substitute' => 'Olive oil',
                'compatibility' => 2,
                'criteria' => 'Healthier option, but different flavor profile',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId5,
                'primary_ingredient' => 'Oil',
                'substitute' => 'Avocado oil',
                'compatibility' => 3,
                'criteria' => 'Healthier option, neutral taste and high heat tolerance',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId5,
                'primary_ingredient' => 'Garlic',
                'substitute' => 'Shallots',
                'compatibility' => 2,
                'criteria' => 'Milder, but similar aromatic quality',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId5,
                'primary_ingredient' => 'Ginger',
                'substitute' => 'Galangal',
                'compatibility' => 2,
                'criteria' => 'Slightly different flavor profile, but still pungent and spicy',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId5,
                'primary_ingredient' => 'Cornstarch',
                'substitute' => 'Potato starch',
                'compatibility' => 3,
                'criteria' => 'Similar thickening agent, works in the same way',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId5,
                'primary_ingredient' => 'Cornstarch',
                'substitute' => 'Arrowroot powder',
                'compatibility' => 3,
                'criteria' => 'Gluten-free, healthier alternative for thickening',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        // Recipe 6: Bok Choy Stir-fry
        $slug6 = Str::slug('Bok Choy Stir-fry');
        $recipeId6 = DB::table('recipes')->insertGetId([
            'title' => 'Bok Choy Stir-fry',
            'slug' => $slug6,
            'description' => 'We all need a go-to green vegetable side dish to go with any main course, and this bok choy stir-fry recipe is a great candidate.',
            'created_by' => 1,
            'image' => 'img/Bok-Choy-Stir-fry.jpg',
            'ingredients' => json_encode(['Bok choy', 'Oil', 'Garlic','Ginger','Salt','Seasame oil','MSG','Cornstarch','White pepper']),
            'steps' => json_encode([
                'Prepare/Wash your Bok Choy:',
                'If using smaller bok choy, cut them into halves lengthwise. Any pieces that look a bit too big can be cut into quarters. This will make them easier to eat and help loosen sand and dirt during washing.' ,
                'Throw the bok choy into a large bowl with lots of cold water. Agitate the veggies with your hands and/or use your faucet sprayer to loosen any dirt. Soak for 5 to 10 minutes (you can leave them for longer if you are prepping other things).' ,
                'Scoop the veggies out of the water into a colander, and rinse the bowl clean of any sand. Repeat the process until you don’t see any dirt on the leaves or at the bottom of your bowl—usually 2 more times will do the trick. On the second or third soak, you can run your fingers on the stems to loosen any stubborn sand.',
                'After the final wash, give your colander of bok choy a few good shakes to release any excess water.',
                'Cooking the Bok Choy:',
                'Heat your wok or a large pan over low heat, and add the oil and ginger. If you prefer a stronger garlicky flavor, add the garlic now. You can let it sizzle in the oil for 10-15 seconds, but don’t let it brown, or it will turn bitter. Add the veggies when the garlic is still white. If you like a fresher, more mild garlic flavor, add it in after salting the vegetables.',
                'Add the veggies, and increase the heat to high. Stir-fry using a scooping motion so the oil and aromatics are evenly distributed.',
                'Next, add salt, sesame oil (if using), the MSG (if using), and the white pepper. Stir-fry for another 1-2 minutes. Finish off with the cornstarch slurry, adding it to the center of the vegetables. Toss the vegetables until they are glistening. Plate and serve immediately.',
            ]),
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        // Substitutions for Recipe 6
        DB::table('substitutions')->insert([
            [
                'recipe_id' => $recipeId6,
                'primary_ingredient' => 'Bok choy',
                'substitute' => 'Napa cabbage',
                'compatibility' => 2,
                'criteria' => 'Similar texture but slightly milder flavor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId6,
                'primary_ingredient' => 'Seasame oil',
                'substitute' => 'Perilla oil',
                'compatibility' => 3,
                'criteria' => 'Flavor profile (rich, nutty),Healthier option (contain omega-3)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId6,
                'primary_ingredient' => 'White pepper',
                'substitute' => 'Black pepper',
                'compatibility' => 2,
                'criteria' => 'More common, similar heat but different flavor profile',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId6,
                'primary_ingredient' => 'Oil',
                'substitute' => 'Olive oil',
                'compatibility' => 2,
                'criteria' => 'Healthier option, but different flavor profile',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId6,
                'primary_ingredient' => 'Oil',
                'substitute' => 'Avocado oil',
                'compatibility' => 3,
                'criteria' => 'Healthier option, neutral taste and high heat tolerance',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId6,
                'primary_ingredient' => 'Garlic',
                'substitute' => 'Shallots',
                'compatibility' => 2,
                'criteria' => 'Milder, but similar aromatic quality',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId6,
                'primary_ingredient' => 'Ginger',
                'substitute' => 'Galangal',
                'compatibility' => 2,
                'criteria' => 'Slightly different flavor profile, but still pungent and spicy',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId6,
                'primary_ingredient' => 'Cornstarch',
                'substitute' => 'Potato starch',
                'compatibility' => 3,
                'criteria' => 'Similar thickening agent, works in the same way',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId6,
                'primary_ingredient' => 'Cornstarch',
                'substitute' => 'Arrowroot powder',
                'compatibility' => 3,
                'criteria' => 'Gluten-free, healthier alternative for thickening',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId6,
                'primary_ingredient' => 'Salt',
                'substitute' => 'Himalayan Salt',
                'compatibility' => 2,
                'criteria' => 'Low in sodium, similar salty profile',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        // Recipe 7: Tomato Potato Soup
        $slug7 = Str::slug('Tomato Potato Soup');
        $recipeId7 = DB::table('recipes')->insertGetId([
            'title' => 'Tomato Potato Soup',
            'slug' => $slug7,
            'description' => 'This simple tomato potato soup is a summer staple, with just 5 ingredients (plus water). It’s a light snack or side dish that replenishes your body with fluids and salt on those sweat-inducing hot days!',
            'created_by' => 1,
            'image' => 'img/Tomato-Potato-Soup.jpg',
            'ingredients' => json_encode(['Tomatoes', 'Oil', 'Potatoes','Water','Scallions']),
            'steps' => json_encode([
                'Prepare the tomatoes and potatoes. If you’re not cooking the soup right away, keep the potatoes in a bowl of cold water to prevent them from oxidizing (turning brown).',
                'Heat oil in a medium soup pot over medium-high heat, and add the tomatoes. Cook for 3-5 minutes, until tomatoes have softened and broken down a bit.' ,
                'Add the water and potato, and bring to a boil over high heat. Once boiling, cover, reduce the heat to medium, and cook for 15 minutes. Finally, add the scallion and salt to taste (don’t be afraid to be generous with the salt). Serve hot or at room temperature!' ,
                ]),
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        // Substitutions for Recipe 7
        DB::table('substitutions')->insert([
            [
                'recipe_id' => $recipeId7,
                'primary_ingredient' => 'Tomatoes',
                'substitute' => 'Tomato paste + water',
                'compatibility' => 2,
                'criteria' => 'Stronger flavor, may need to adjust for balance',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId7,
                'primary_ingredient' => 'Potatoes',
                'substitute' => 'Sweet potatoes',
                'compatibility' => 2,
                'criteria' => 'Different flavor, adds natural sweetness',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId7,
                'primary_ingredient' => 'Oil',
                'substitute' => 'Olive oil',
                'compatibility' => 2,
                'criteria' => 'Healthier option, but different flavor profile',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId7,
                'primary_ingredient' => 'Oil',
                'substitute' => 'Avocado oil',
                'compatibility' => 3,
                'criteria' => 'Healthier option, neutral taste and high heat tolerance',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId7,
                'primary_ingredient' => 'Water',
                'substitute' => 'Vegetable broth',
                'compatibility' => 3,
                'criteria' => 'Adds depth of flavor, ideal for a richer soup',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId7,
                'primary_ingredient' => 'Water',
                'substitute' => 'Chicken broth',
                'compatibility' => 2,
                'criteria' => 'Adds savory richness, but not suitable for vegans/vegetarians',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId7,
                'primary_ingredient' => 'Scallions',
                'substitute' => 'Chives',
                'compatibility' => 2,
                'criteria' => 'Milder flavor but similar freshness',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        // Recipe 8: Coconut Curry Shrimp
        $slug8 = Str::slug('Coconut Curry Shrimp');
        $recipeId8 = DB::table('recipes')->insertGetId([
            'title' => 'Coconut Curry Shrimp',
            'slug' => $slug8,
            'description' => 'This simple coconut curry shrimp in a delicious red curry sauce will have you enjoying a restaurant experience at home on any day of the week. With just 9 ingredients (and 2 optional ones) and 30 minutes of time in the kitchen, cooking dinner might be easier—and certainly cheaper—than going out or ordering takeout!',
            'created_by' => 1,
            'image' => 'img/Coconut-Curry-Shrimp.jpg',
            'ingredients' => json_encode(['Shrimp', 'Oil', 'Red bell pepper','Garlic','Full-fat coconut milk','Brown sugar','Thai red curry paste']),
            'steps' => json_encode([
                'Heat a wok or large skillet over medium-high heat until. Add 1 tablespoon of oil, and spread it around to coat. Add the shrimp, and allow it to sear for 30 seconds on 1 side. Then stir-fry for 30 seconds, until the shrimp is 75% cooked (it should be mostly opaque). Turn off the heat, remove the shrimp to a bowl, and set aside.',
                'Over medium heat, add the remaining tablespoon of oil to the pan, along with the garlic and ginger. Fry for 30 seconds, until fragrant. Increase the heat to medium-high, add the curry paste, and fry for another minute. Stir in the brown sugar. Then add the onion and pepper, and fry for 2 minutes.' ,
                'Add the coconut milk. Bring to a simmer over medium-high heat. (From this point on, keep the curry at a simmer. Avoid boiling it too vigorously, or the coconut milk may split and have a grainy appearance.) Simmer for 2 minutes to thicken the sauce and cook the onions down.' ,
                'Stir in the shrimp, and simmer for 1 more minute. Taste and season with additional salt if needed (particularly if you used less curry paste). Garnish with cilantro if desired, and serve!'
                ]),
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        // Substitutions for Recipe 8
        DB::table('substitutions')->insert([
            [
                'recipe_id' => $recipeId8,
                'primary_ingredient' => 'Shrimp',
                'substitute' => 'Tofu',
                'compatibility' => 3,
                'criteria' => 'Vegan option, different texture but a solid protein replacement',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId8,
                'primary_ingredient' => 'Shrimp',
                'substitute' => 'Chicken Breast',
                'compatibility' => 2,
                'criteria' => 'Similar texture, different flavor, non-seafood alternative',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId8,
                'primary_ingredient' => 'Oil',
                'substitute' => 'Olive oil',
                'compatibility' => 2,
                'criteria' => 'Healthier option, but different flavor profile',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId8,
                'primary_ingredient' => 'Oil',
                'substitute' => 'Avocado oil',
                'compatibility' => 3,
                'criteria' => 'Healthier option, neutral taste and high heat tolerance',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId8,
                'primary_ingredient' => 'Garlic',
                'substitute' => 'Garlic powder',
                'compatibility' => 1,
                'criteria' => 'Flavor replacement, lacks texture',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId8,
                'primary_ingredient' => 'Garlic',
                'substitute' => 'Galangal',
                'compatibility' => 2,
                'criteria' => 'Similar flavor, used in Thai cuisine, slightly more aromatic',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId8,
                'primary_ingredient' => 'Red bell pepper',
                'substitute' => 'Yellow bell pepper',
                'compatibility' => 2,
                'criteria' => 'Similar texture, different color and slightly sweeter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId8,
                'primary_ingredient' => 'Red bell pepper',
                'substitute' => 'Green bell pepper',
                'compatibility' => 2,
                'criteria' => 'More bitter, but same crunchy texture',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId8,
                'primary_ingredient' => 'Full-fat coconut milk',
                'substitute' => 'Light coconut milk',
                'compatibility' => 3,
                'criteria' => 'Lower fat content but similar creamy texture',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId8,
                'primary_ingredient' => 'Full-fat coconut milk',
                'substitute' => 'Almond milk',
                'compatibility' => 1,
                'criteria' => 'Lacks creaminess, but can replace for dietary reasons (non-dairy)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId8,
                'primary_ingredient' => 'Brown sugar',
                'substitute' => 'Coconut sugar',
                'compatibility' => 3,
                'criteria' => 'Healthier option, similar sweetness',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId8,
                'primary_ingredient' => 'Brown sugar',
                'substitute' => 'Maple syrup',
                'compatibility' => 2,
                'criteria' => 'Different texture but similar natural sweetness',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId8,
                'primary_ingredient' => 'Thai red curry paste',
                'substitute' => 'Yellow curry paste',
                'compatibility' => 2,
                'criteria' => 'Milder flavor but similar spice base',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'recipe_id' => $recipeId8,
                'primary_ingredient' => 'Thai red curry paste',
                'substitute' => 'Green curry paste',
                'compatibility' => 2,
                'criteria' => 'Similar but more herbaceous',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        // Ensure all recipes have a valid slug
        $recipes = DB::table('recipes')->get();

        foreach ($recipes as $recipe) {
            DB::table('recipes')
                ->where('id', $recipe->id)
                ->update(['slug' => Str::slug($recipe->title)]);
        }
    }

}
